version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres_sql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jAeczQQX3bd60Hb
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_web
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db